export const STUDY_NOTES_ENABLED = true;
export const STUDY_ANKI_ENABLED = true;
export const STUDY_FOCUS_ENABLED = true;
export const STUDY_PROGRESS_ENABLED = true;
export const STUDY_ACHIEVEMENTS_ENABLED = true;

export const STUDY_MAINTENANCE_NOTICE = !STUDY_FOCUS_ENABLED
  || !STUDY_PROGRESS_ENABLED
  || !STUDY_ACHIEVEMENTS_ENABLED
  || !STUDY_NOTES_ENABLED;
